name: example
description: Charts-Flutter Demo
environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=3.16.2'

dependencies:
  charts_flutter:
    path: ../
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.10.0
  intl: 0.18.0
flutter:
  uses-material-design: true
